name: CI workflow

on:
  push:
    branches: 
      - main
  pull_request:
    branches:
      - main
  
jobs:
  build:                          # build is the name of a job
    runs-on: "ubuntu-latest"
    container: "python:3.9-slim"
